### ISSUE TITLE
טקסט על הקיר

### ISSUE THREAD

**Issue by erelsgl** [GangCS/SWAP#3]
כשהטקסט כתוב על הקיר, השחקן רואה אותו בענק וזה עלול לבלבל.
עדיף לשים את הטקסט על 
Canvas
שנשאר בגודל קבוע ובמיקום קבוע על המסך (ונעלם כשהשחקן סוגר אותו).
תבדקו איך זה עובד בפורטל.

**Comment by VadimKachevski** [comment]
טופל, יש הסברים בשלב הדרכה, השארנו טיפה טקסט על הקיר בשלב הראשון בשביל לתת חיזוק להדרכה בנקודות החשובות.
