### ISSUE TITLE
עיצוב המסכים הראשונים

### ISSUE THREAD

**Issue by erelsgl** [GangCS/SWAP#4]
בגדול יפה מאד. הייתי מוסיף במסכים הראשונים חץ על הרצפה שמראה לשחקן את הכיוון "קדימה", כדי שיבין לאן הוא צריך להתקדם  (זה עלול להיות מבלבל בגלל ההחלפות).

הייתי גם מוסיף חדר ראשון ריק, שבו השחקן יכול רק להתחלף עם קוביה, כדי שיבין את המנגנון - כיוון שזה המנגנון העיקרי של המשחק. בחדר הזה אפשר להוסיף את סיפור-הרקע של המשחק (כמו שכתבתם ברידמי).

**Comment by VadimKachevski** [comment]
בוצע בניית חדר הדרכה כמסלול ישר עם דלתות שמכיוונות את השחקן.
